# GCP Cloud Build 설정
# Frontend + Backend 이미지를 Artifact Registry에 빌드 및 푸시

steps:
  # ========================================
  # Frontend 빌드
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    env:
      - 'DOCKER_BUILDKIT=1'  # BuildKit 활성화 (--mount 옵션 지원)
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-frontend:latest'
      # 최초 빌드 시 캐시 옵션 제거 (이미지 생성 후 주석 해제)
      # - '--cache-from'
      # - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-frontend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - './frontend/Dockerfile'
      - './frontend'
    waitFor: ['-']  # 병렬 실행

  # ========================================
  # Backend 빌드
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    env:
      - 'DOCKER_BUILDKIT=1'  # BuildKit 활성화 (--mount 옵션 지원)
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-backend:latest'
      # 최초 빌드 시 캐시 옵션 제거 (이미지 생성 후 주석 해제)
      # - '--cache-from'
      # - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-backend:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-f'
      - './backend/Dockerfile'
      - './backend'
    waitFor: ['-']  # 병렬 실행

  # ========================================
  # 이미지 푸시 (Frontend)
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-frontend:latest'
    waitFor: ['build-frontend']

  # ========================================
  # 이미지 푸시 (Backend)
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-backend:latest'
    waitFor: ['build-backend']

# Artifact Registry에 푸시할 이미지 목록
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-frontend:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/stock-backend:latest'

# 빌드 타임아웃 (전체 빌드 시간 제한)
timeout: '1200s'

# 빌드 옵션
options:
  # 고성능 빌드 머신 사용 (8 vCPU)
  machineType: 'E2_HIGHCPU_8'

  # 디스크 크기 (GB)
  diskSizeGb: 50

  # 로깅
  logging: CLOUD_LOGGING_ONLY

# 빌드 대체 변수 (substitutions)
# CLI에서 --substitutions로 오버라이드 가능
substitutions:
  _REGION: 'us-central1'       # Iowa, USA 리전
  _REPOSITORY: 'stock-app'     # Artifact Registry 저장소 이름
